"""
Pydantic schemas (request/response models) used by the API layer.

These models define the shape of:
- incoming payloads in POST/PUT requests,
- outgoing responses returned by CRUD operations,
- analytical results returned by dashboard endpoints.

Schemas mirror the structure of SQLAlchemy ORM models but are decoupled
so the API never exposes internal database objects directly.
"""

from pydantic import BaseModel


# ----------------------------------------------------------------------
# Product Schemas
# ----------------------------------------------------------------------
class ProductBase(BaseModel):
    """
    Base shared schema for product data.

    Represents the fields that are common across:
    - product creation (POST)
    - product responses (GET)

    Fields mirror the `Product` ORM model.
    """

    product_sku: int
    # Unique SKU identifier for the product.

    product_name: str
    # Human-readable name of the product.

    category: str | None = None
    # Optional product category (e.g., "Skincare").

    brand: str | None = None
    # Optional brand field.

    price: float
    # Unit price of the product.


class ProductCreate(ProductBase):
    """
    Schema for creating a new product.

    Inherits all fields from ProductBase.
    Typically used in POST /products.
    """
    pass


class Product(ProductBase):
    """
    Schema returned for product responses.

    Includes ORM mode so SQLAlchemy objects can be converted
    to Pydantic models automatically.
    """

    class Config:
        orm_mode = True


# ----------------------------------------------------------------------
# Analytics Schemas
# ----------------------------------------------------------------------
class TopProduct(BaseModel):
    """
    Schema representing the result of a revenue-based query.

    Returned by analytics endpoints such as:
    - top-selling products
    - total revenue per SKU

    Fields:
        product_sku: SKU identifier.
        product_name: Product name (may be null if joined from sales only).
        total_revenue: Total revenue generated by this SKU.
    """

    product_sku: int
    product_name: str | None = None
    total_revenue: float
